name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  # Push image to Docker Hub.
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}
          repository: candrews74/diet-tracker-ui
          build_args: API_URL=https://diet-tracker.pollyspeople.net,REACT_APP_AUTH0_DOMAIN=dev-clinta74.us.auth0.com,REACT_APP_AUTH0_CLIENT_ID=I1EPbV0JzhQ4sMebkA5XSg0RhYhJBa1k,REACT_APP_AUTH0_AUDIENCE=https://diet-tracker.pollyspeople.net
          tag_with_ref: true